const state={operators:[],filtered:[],changes:[]};
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=name=>name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const statusLabel=s=>({'scraped':'Detected','needs-review':'Needs review','unavailable':'Unavailable'})[s]||'Unknown';
function formatDate(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(d)+' UTC'}
function relativeDate(value){if(!value)return'Unknown';const n=Date.now()-new Date(value).getTime();if(n<60000)return'just now';if(n<3600000)return`${Math.floor(n/60000)}m ago`;if(n<86400000)return`${Math.floor(n/3600000)}h ago`;return`${Math.floor(n/86400000)}d ago`}
async function load(){try{const r=await fetch(`data.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();state.operators=Array.isArray(data.operators)?data.operators:[];state.changes=Array.isArray(data.changes)?data.changes:[];$('#last-updated').textContent=`Dataset updated ${formatDate(data.lastUpdated)}`;$('#hero-updated').textContent=relativeDate(data.lastUpdated);$('#system-status').textContent='Operational';renderMetrics();applyFilters();renderChanges();}catch(e){console.error(e);$('#system-status').textContent='Data error';$('#last-updated').textContent='Could not load data.json';$('#operator-list').innerHTML='<div class="empty-state"><strong>Dataset unavailable</strong><span>Confirm that data.json exists in the repository root.</span></div>'}}
function renderMetrics(){const o=state.operators;const vals={total:o.length,detected:o.filter(x=>x.status==='scraped').length,review:o.filter(x=>x.status==='needs-review').length,unavailable:o.filter(x=>x.status==='unavailable').length};$('#metric-total').textContent=vals.total;$('#metric-detected').textContent=vals.detected;$('#metric-review').textContent=vals.review;$('#metric-unavailable').textContent=vals.unavailable;$('#hero-operators').textContent=vals.total;$('#hero-changes').textContent=state.changes.length}
function applyFilters(){const q=$('#search-input').value.trim().toLowerCase();const status=$('#status-filter').value;const sort=$('#sort-select').value;state.filtered=state.operators.filter(o=>(status==='all'||o.status===status)&&(!q||`${o.name} ${o.bonus||o.scrapedText||''}`.toLowerCase().includes(q)));state.filtered.sort((a,b)=>sort==='recent'?new Date(b.checkedAt)-new Date(a.checkedAt):sort==='status'?(a.status||'').localeCompare(b.status||''):(a.name||'').localeCompare(b.name||''));renderOperators()}
function renderOperators(){const list=$('#operator-list');const empty=$('#empty-state');empty.hidden=state.filtered.length>0;list.innerHTML=state.filtered.map((o,i)=>`<article class="operator-row"><div class="operator-name"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="avatar">${escapeHtml(initials(o.name||'?'))}</span><span><strong>${escapeHtml(o.name||'Unknown')}</strong><small>${escapeHtml(new URL(o.url||'https://example.com').hostname.replace('www.',''))}</small></span></div><div class="offer-text">${escapeHtml(o.bonus||o.scrapedText||'No reliable public text detected.')}</div><span class="badge ${escapeHtml(o.status||'needs-review')}">${escapeHtml(statusLabel(o.status))}</span><span class="checked">${escapeHtml(relativeDate(o.checkedAt))}</span><button class="detail-button" data-index="${state.operators.indexOf(o)}">View</button></article>`).join('');list.querySelectorAll('.detail-button').forEach(b=>b.addEventListener('click',()=>openDetail(state.operators[Number(b.dataset.index)])))}
function renderChanges(){const root=$('#change-list');const changes=state.changes.length?state.changes:state.operators.slice(0,3).map(o=>({operator:o.name,type:o.status==='scraped'?'Text detected':'Review status',summary:o.bonus||'No reliable public text detected.',detectedAt:o.checkedAt}));root.innerHTML=changes.slice(0,6).map(c=>`<article class="change-card"><div class="change-top"><strong>${escapeHtml(c.operator||'Operator')}</strong><time>${escapeHtml(relativeDate(c.detectedAt))}</time></div><span class="badge needs-review">${escapeHtml(c.type||'Update')}</span><p>${escapeHtml(c.summary||'Record updated.')}</p></article>`).join('')}
function openDetail(o){$('#dialog-content').innerHTML=`<p class="kicker">OPERATOR RECORD</p><h2>${escapeHtml(o.name||'Unknown')}</h2><div class="dialog-offer">${escapeHtml(o.bonus||o.scrapedText||'No reliable public text detected.')}</div><div class="dialog-grid"><div class="dialog-field"><span>Status</span><strong>${escapeHtml(statusLabel(o.status))}</strong></div><div class="dialog-field"><span>Checked</span><strong>${escapeHtml(formatDate(o.checkedAt))}</strong></div><div class="dialog-field"><span>Source domain</span><strong>${escapeHtml((()=>{try{return new URL(o.url).hostname}catch{return'Unknown'}})())}</strong></div><div class="dialog-field"><span>Verification</span><strong>${o.status==='scraped'?'Automated detection':'Manual review required'}</strong></div></div><p style="color:var(--muted);font-size:13px;margin-top:18px">Automated detection is not an independent confirmation of eligibility, accuracy or availability.</p>`;$('#detail-dialog').showModal()}
$('#search-input').addEventListener('input',applyFilters);$('#status-filter').addEventListener('change',applyFilters);$('#sort-select').addEventListener('change',applyFilters);$('#dialog-close').addEventListener('click',()=>$('#detail-dialog').close());$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog'))$('#detail-dialog').close()});$('#theme-toggle').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('betintel-theme',document.body.classList.contains('light')?'light':'dark')});if(localStorage.getItem('betintel-theme')==='light')document.body.classList.add('light');$('#year').textContent=new Date().getFullYear();load();
