const state={operators:[],filtered:[],changes:[],history:{operators:{}},selected:[]};
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slugify=v=>String(v??'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const initials=name=>String(name||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const statusLabel=s=>({'scraped':'Detected','needs-review':'Needs review','unavailable':'Unavailable'})[s]||'Unknown';
function formatDate(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(d)+' UTC'}
function relativeDate(value){if(!value)return'Unknown';const t=new Date(value).getTime();if(Number.isNaN(t))return'Unknown';const n=Math.max(0,Date.now()-t);if(n<60000)return'just now';if(n<3600000)return`${Math.floor(n/60000)}m ago`;if(n<86400000)return`${Math.floor(n/3600000)}h ago`;return`${Math.floor(n/86400000)}d ago`}
function safeHost(value){try{return new URL(value).hostname.replace('www.','')}catch{return'Unknown'}}
async function load(){
  try{
    const [dataResponse,historyResponse]=await Promise.all([
      fetch(`data.json?v=${Date.now()}`,{cache:'no-store'}),
      fetch(`history.json?v=${Date.now()}`,{cache:'no-store'}).catch(()=>null)
    ]);
    if(!dataResponse.ok)throw new Error(`HTTP ${dataResponse.status}`);
    const data=await dataResponse.json();
    state.operators=Array.isArray(data.operators)?data.operators:[];
    state.changes=Array.isArray(data.changes)?data.changes:[];
    if(historyResponse?.ok)state.history=await historyResponse.json();
    $('#last-updated').textContent=`Dataset updated ${formatDate(data.lastUpdated)}`;
    $('#hero-updated').textContent=relativeDate(data.lastUpdated);
    $('#system-status').textContent='Operational';
    renderMetrics();applyFilters();renderChanges();renderCompareSlots();
  }catch(e){
    console.error(e);$('#system-status').textContent='Data error';$('#last-updated').textContent='Could not load data.json';
    $('#operator-list').innerHTML='<div class="empty-state"><strong>Dataset unavailable</strong><span>Confirm that data.json exists in the repository root.</span></div>';
  }
}
function renderMetrics(){const o=state.operators;const vals={total:o.length,detected:o.filter(x=>x.status==='scraped').length,review:o.filter(x=>x.status==='needs-review').length,unavailable:o.filter(x=>x.status==='unavailable').length};$('#metric-total').textContent=vals.total;$('#metric-detected').textContent=vals.detected;$('#metric-review').textContent=vals.review;$('#metric-unavailable').textContent=vals.unavailable;$('#hero-operators').textContent=vals.total;$('#hero-changes').textContent=state.changes.length}
function applyFilters(){const q=$('#search-input').value.trim().toLowerCase();const status=$('#status-filter').value;const sort=$('#sort-select').value;state.filtered=state.operators.filter(o=>(status==='all'||o.status===status)&&(!q||`${o.name} ${o.bonus||o.scrapedText||''}`.toLowerCase().includes(q)));state.filtered.sort((a,b)=>sort==='recent'?new Date(b.checkedAt)-new Date(a.checkedAt):sort==='status'?(a.status||'').localeCompare(b.status||''):(a.name||'').localeCompare(b.name||''));renderOperators()}
function renderOperators(){
  const list=$('#operator-list'),empty=$('#empty-state');empty.hidden=state.filtered.length>0;
  list.innerHTML=state.filtered.map((o,i)=>{const globalIndex=state.operators.indexOf(o),selected=state.selected.includes(globalIndex);return `<article class="operator-row"><div class="operator-name"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="avatar">${escapeHtml(initials(o.name))}</span><span><strong>${escapeHtml(o.name||'Unknown')}</strong><small>${escapeHtml(safeHost(o.url))}</small></span></div><div class="offer-text">${escapeHtml(o.bonus||o.scrapedText||'No reliable public text detected.')}</div><span class="badge ${escapeHtml(o.status||'needs-review')}">${escapeHtml(statusLabel(o.status))}</span><span class="checked">${escapeHtml(relativeDate(o.checkedAt))}</span><div class="row-actions"><button class="icon-detail history-button" data-index="${globalIndex}" title="View history">↗</button><button class="detail-button select-button ${selected?'selected':''}" data-index="${globalIndex}">${selected?'Selected':'Compare'}</button><button class="detail-button view-button" data-index="${globalIndex}">View</button></div></article>`}).join('');
  list.querySelectorAll('.view-button').forEach(b=>b.addEventListener('click',()=>openDetail(state.operators[Number(b.dataset.index)])));
  list.querySelectorAll('.history-button').forEach(b=>b.addEventListener('click',()=>openHistory(state.operators[Number(b.dataset.index)])));
  list.querySelectorAll('.select-button').forEach(b=>b.addEventListener('click',()=>toggleCompare(Number(b.dataset.index))));
}
function renderChanges(){const root=$('#change-list');const changes=state.changes.length?state.changes:state.operators.slice(0,3).map(o=>({operator:o.name,type:o.status==='scraped'?'Text detected':'Review status',summary:o.bonus||'No reliable public text detected.',detectedAt:o.checkedAt}));root.innerHTML=changes.slice(0,6).map(c=>`<article class="change-card"><div class="change-top"><strong>${escapeHtml(c.operator||'Operator')}</strong><time>${escapeHtml(relativeDate(c.detectedAt))}</time></div><span class="badge needs-review">${escapeHtml(c.type||'Update')}</span><p>${escapeHtml(c.summary||'Record updated.')}</p></article>`).join('')}
function toggleCompare(index){const pos=state.selected.indexOf(index);if(pos>=0)state.selected.splice(pos,1);else if(state.selected.length<3)state.selected.push(index);else{alert('You can compare up to three operators.');return}renderOperators();renderCompareSlots()}
function renderCompareSlots(){const root=$('#compare-slots');const selected=state.selected.map(i=>state.operators[i]).filter(Boolean);const slots=[0,1,2].map(i=>{const o=selected[i];return o?`<article class="compare-slot filled"><span class="avatar">${escapeHtml(initials(o.name))}</span><div><strong>${escapeHtml(o.name)}</strong><small>${escapeHtml(statusLabel(o.status))}</small></div><button data-position="${i}" aria-label="Remove ${escapeHtml(o.name)}">×</button></article>`:`<article class="compare-slot"><span>${i+1}</span><div><strong>Select an operator</strong><small>Use Compare in the table</small></div></article>`}).join('');root.innerHTML=slots;root.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.selected.splice(Number(b.dataset.position),1);renderOperators();renderCompareSlots()}));$('#compare-button').disabled=selected.length<2}
function renderComparison(){const selected=state.selected.map(i=>state.operators[i]).filter(Boolean);if(selected.length<2)return;const root=$('#compare-result');const rows=[['Status',o=>statusLabel(o.status)],['Detected public text',o=>o.bonus||o.scrapedText||'No reliable public text detected.'],['Source domain',o=>safeHost(o.url)],['Last checked',o=>formatDate(o.checkedAt)],['History records',o=>(state.history.operators?.[slugify(o.name)]||[]).length]];root.innerHTML=`<div class="comparison-table"><div class="comparison-row comparison-head"><span>Field</span>${selected.map(o=>`<strong>${escapeHtml(o.name)}</strong>`).join('')}</div>${rows.map(([label,get])=>`<div class="comparison-row"><span>${escapeHtml(label)}</span>${selected.map(o=>`<div>${escapeHtml(get(o))}</div>`).join('')}</div>`).join('')}</div><p class="comparison-note">Comparison reflects the latest stored dataset. Automated detections are not independent verification.</p>`;root.scrollIntoView({behavior:'smooth',block:'nearest'})}
function openHistory(o){const records=state.history.operators?.[slugify(o.name)]||[];$('#history-content').innerHTML=`<p class="kicker">BONUS HISTORY</p><h2>${escapeHtml(o.name||'Unknown')}</h2>${records.length?`<div class="history-timeline">${[...records].reverse().map((r,i)=>`<article><span class="timeline-dot"></span><div><div class="timeline-meta"><strong>${i===0?'Latest record':'Historical record'}</strong><time>${escapeHtml(formatDate(r.checkedAt))}</time></div><p>${escapeHtml(r.bonus||'No text stored.')}</p><span class="badge ${escapeHtml(r.status||'needs-review')}">${escapeHtml(statusLabel(r.status))}</span></div></article>`).join('')}</div>`:'<div class="empty-state"><strong>No history yet</strong><span>The daily updater will begin adding records after the next scan.</span></div>'}`;$('#history-dialog').showModal()}
function openDetail(o){$('#dialog-content').innerHTML=`<p class="kicker">OPERATOR RECORD</p><h2>${escapeHtml(o.name||'Unknown')}</h2><div class="dialog-offer">${escapeHtml(o.bonus||o.scrapedText||'No reliable public text detected.')}</div><div class="dialog-grid"><div class="dialog-field"><span>Status</span><strong>${escapeHtml(statusLabel(o.status))}</strong></div><div class="dialog-field"><span>Checked</span><strong>${escapeHtml(formatDate(o.checkedAt))}</strong></div><div class="dialog-field"><span>Source domain</span><strong>${escapeHtml(safeHost(o.url))}</strong></div><div class="dialog-field"><span>History records</span><strong>${(state.history.operators?.[slugify(o.name)]||[]).length}</strong></div></div><div class="dialog-actions"><button class="secondary-button" id="detail-history" type="button">View history</button></div><p class="dialog-note">Automated detection is not an independent confirmation of eligibility, accuracy or availability.</p>`;$('#detail-dialog').showModal();$('#detail-history').addEventListener('click',()=>{$('#detail-dialog').close();openHistory(o)})}
$('#search-input').addEventListener('input',applyFilters);$('#status-filter').addEventListener('change',applyFilters);$('#sort-select').addEventListener('change',applyFilters);$('#compare-button').addEventListener('click',renderComparison);$('#dialog-close').addEventListener('click',()=>$('#detail-dialog').close());$('#history-close').addEventListener('click',()=>$('#history-dialog').close());['#detail-dialog','#history-dialog'].forEach(sel=>$(sel).addEventListener('click',e=>{if(e.target===$(sel))$(sel).close()}));$('#theme-toggle').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('betintel-theme',document.body.classList.contains('light')?'light':'dark')});if(localStorage.getItem('betintel-theme')==='light')document.body.classList.add('light');$('#year').textContent=new Date().getFullYear();load();
